# Generated by Django 2.1.3 on 2019-01-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_id', models.BooleanField(default=False, verbose_name='是否删除')),
                ('author', models.CharField(max_length=20, verbose_name='评论者')),
                ('con', models.TextField(max_length=1000, verbose_name='评论内容')),
                ('u_id', models.IntegerField(max_length=10, verbose_name='被评论者ID')),
            ],
            options={
                'verbose_name_plural': '评论表',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_id', models.BooleanField(default=False, verbose_name='是否删除')),
                ('author', models.CharField(max_length=20, verbose_name='发布者')),
                ('con', models.TextField(max_length=1000, verbose_name='动态内容')),
                ('z_number', models.IntegerField(max_length=1000, verbose_name='获赞量')),
            ],
            options={
                'verbose_name_plural': '动态表',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_id', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='菜名')),
                ('img', models.ImageField(default='', upload_to='', verbose_name='图像')),
                ('introduce', models.TextField(max_length=1000, verbose_name='介绍')),
                ('ingres', models.TextField(max_length=50, verbose_name='食材')),
                ('step', models.TextField(max_length=3000, verbose_name='步骤')),
                ('score', models.IntegerField(max_length=10, verbose_name='评分')),
            ],
            options={
                'verbose_name_plural': '菜谱表',
            },
        ),
        migrations.CreateModel(
            name='Mtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_id', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=20, verbose_name='类名')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Menu', verbose_name='菜谱ID')),
            ],
            options={
                'verbose_name_plural': '菜谱分类表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_id', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('phone', models.IntegerField(max_length=20, verbose_name='手机号')),
                ('password', models.IntegerField(max_length=20, verbose_name='密码')),
                ('type', models.IntegerField(choices=[(0, '用户'), (1, '商家')], default=0, verbose_name='类型')),
                ('photo', models.ImageField(default='', upload_to='', verbose_name='头像')),
                ('follow', models.IntegerField(default=0, max_length=20, verbose_name='关注量')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
