# Generated by Django 2.1.3 on 2019-01-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='introduce',
        ),
        migrations.AddField(
            model_name='menu',
            name='bq',
            field=models.CharField(default='', max_length=50, verbose_name='标签'),
        ),
    ]
