# Generated by Django 2.1.3 on 2019-01-09 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitchen', '0002_auto_20190108_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_id', models.BooleanField(default=False, verbose_name='是否删除')),
                ('phone', models.IntegerField(verbose_name='手机号')),
                ('type', models.IntegerField(choices=[(0, '用户'), (1, '商家')], default=0, verbose_name='类型')),
                ('photo', models.ImageField(default='', upload_to='', verbose_name='头像')),
                ('follow', models.IntegerField(default=0, verbose_name='关注量')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='comment',
            name='u_id',
            field=models.IntegerField(verbose_name='被评论者ID'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='z_number',
            field=models.IntegerField(verbose_name='获赞量'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='score',
            field=models.IntegerField(verbose_name='评分'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
