# Generated by Django 2.1.3 on 2019-01-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_auto_20190109_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtype',
            name='m_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='c_time',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='del_id',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='u_time',
        ),
        migrations.DeleteModel(
            name='Mtype',
        ),
    ]
